config/routes.rb
Rails.application.routes.draw do
resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end


  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      @event = Event.new(event_params)
      render:new
    end
  end


  def show
    @event = Event.find(params[:id])
  end


  def edit
    @event = Event.find(params[:id])
  end


  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)

      redirect_to events_path
    else
      render :edit
    end
  end
  

    private

    def event_params
      params.require(:event).permit(:date, :location, :description, :capacity, :requires_id)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<%= form_for @event, url: event_path(@event), method: :patch do |f| %>
<div>
  <%= f.label :date %>
  <%= f.date_field :date %>
</div>

</br>

<div>
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>

</br>

<div>
<%= f.label :descripton %>
<%= f.text_field :description %>
</div>

</br>

<div>
<%= f.label :capacity %>
<%= f.number_field :capacity %>
</div>

</br>

<div>
<%= f.label :name, 'Requires ID' %>
<%= f.check_box :requires_id %>
</div>

</br>

<%= f.submit "Submit Edits" %>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
<div>
<p><%= event.date %></p>
<p><%= event.location %></p>
<p><%= event.description %></p>
<p><%= event.capacity %></p>
<p><%= event.requires_id %></p>
<p><%= link_to "Show", event_path(event[:id]) %></p>

</div>


<% end %>

app/views/events/new.html.erb
<h2> Please enter your new event info:</h2 >

<%= form_for @event do |f| %>
  <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

</br>

  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

</br>

<div>
  <%= f.label :descripton %>
  <%= f.text_field :description %>
</div>

</br>

<div>
  <%= f.label :capacity %>
  <%= f.number_field :capacity %>
</div>

</br>

<div>
  <%= f.label :name, 'Requires ID' %>
  <%= f.check_box :requires_id %>
</div>

</br>

  <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<%= @event.date %>
<%= @event.location %>
<%= @event.description %>
<%= @event.capacity %>
<%= @event.requires_id %>
<br>
<%= link_to 'Edit', edit_event_path(@event) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>